name: MD to RTF
description: Use this action to convert markdown files to rich text file.
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  
    - name: Checkout Action
      uses: actions/checkout@v4
      with:
        repository: nb-winterbourne/action-md-to-rtf
        path: actions
        token: ${{ env.TOKEN }}
    - name: Install Dependencies
      run: pip3 install -r actions/requirements.txt
      shell: bash
    - name: Install Pandoc
      run: sudo apt-get install pandoc
      shell: bash
    - name: Run converter and deposit
      id: convert-and-deposit
      run: python3 actions/main.py
      shell: bash
    - name: Commit output files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
          echo "push=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Add changes" -a
          echo "push=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.TOKEN }}