name: MD to RTF
description: Use this action to convert markdown files to rich text file.
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  
    - name: Checkout Action
      uses: actions/checkout@v4
      with:
        repository: nb-winterbourne/action-md-to-rtf
        path: actions
        token: ${{ env.TOKEN }}
    - name: Install Dependencies
      run: pip3 install -r actions/requirements.txt
      shell: bash
    - name: Run converter and deposit
      id: convert-and-deposit
      run: python3 actions/main.py
      shell: bash